# Generated by Django 4.2.6 on 2023-10-14 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('ActividadID', models.AutoField(primary_key=True, serialize=False)),
                ('EventoID', models.IntegerField()),
                ('Creador', models.IntegerField()),
                ('Descripcion', models.TextField()),
                ('ValorTotal', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('EventoID', models.AutoField(primary_key=True, serialize=False)),
                ('Creador', models.IntegerField()),
                ('Nombre', models.CharField(max_length=255)),
                ('Descripcion', models.TextField(blank=True, null=True)),
                ('Tipo', models.CharField(max_length=10)),
                ('FotoOAvatar', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('CorreoElectronico', models.CharField(max_length=255, unique=True)),
                ('NombreCompleto', models.CharField(max_length=255)),
                ('Apodo', models.CharField(max_length=255)),
                ('FotoOAvatar', models.CharField(max_length=512)),
                ('Estado', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Saldos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendApp.eventos')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendApp.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantesEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendApp.eventos')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendApp.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantesActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ActividadID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendApp.actividades')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendApp.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AcreedorUserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_acreedor', to='backendApp.usuarios')),
                ('DeudorUserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_deudor', to='backendApp.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CorreoElectronico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos_correo', to='backendApp.usuarios')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos_usuario', to='backendApp.usuarios')),
            ],
        ),
    ]
