# Generated by Django 4.2.6 on 2023-10-26 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0005_alter_usuarios_fotooavatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwords',
            name='UserID',
        ),
        migrations.RemoveField(
            model_name='passwords',
            name='id',
        ),
        migrations.AddField(
            model_name='passwords',
            name='CorreoElectronico',
            field=models.OneToOneField(default='default@example.com', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backendApp.usuarios', to_field='CorreoElectronico'),
            preserve_default=False,
        ),
    ]
