# Generated by Django 4.2.6 on 2023-10-26 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0006_remove_passwords_userid_remove_passwords_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwords',
            name='PasswordID',
            field=models.AutoField(default='1', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='passwords',
            name='CorreoElectronico',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backendApp.usuarios', to_field='CorreoElectronico'),
        ),
    ]
