# Generated by Django 4.2.6 on 2023-11-27 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividades',
            name='Nombre',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventos',
            name='FotoOAvatar',
            field=models.CharField(choices=[('https://w7.pngwing.com/pngs/980/935/png-transparent-clapperboard-architecture-sports-activities-text-fashion-logo-thumbnail.png', 'avatar 1'), ('https://png.pngtree.com/png-clipart/20220628/original/pngtree-food-logo-png-image_8239850.png', 'avatar 2'), ('https://logo.com/image-cdn/images/kts928pd/production/cbe600c9fc90afe063527b300816e390f57a8915-349x346.png', 'avatar 3'), ('https://assets.stickpng.com/images/590605810cbeef0acff9a63c.png', 'avatar 4'), ('https://logowik.com/content/uploads/images/google-shopping.jpg', 'avatar 5'), ('https://png.pngtree.com/png-clipart/20230921/original/pngtree-swimming-logo-logo-pool-white-vector-png-image_12645079.png', 'avatar 6')], default='https://assets.stickpng.com/images/590605810cbeef0acff9a63c.png', max_length=255),
        ),
    ]
