# Generated by Django 4.2.6 on 2023-11-09 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_alter_contactos_emisor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividades',
            options={'ordering': ['ActividadID'], 'verbose_name': 'Actividad', 'verbose_name_plural': 'Actividades'},
        ),
        migrations.AlterModelOptions(
            name='contactos',
            options={'ordering': ['ContactID'], 'verbose_name': 'Contacto', 'verbose_name_plural': 'Contactos'},
        ),
        migrations.AlterModelOptions(
            name='eventos',
            options={'ordering': ['EventoID'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='pagos',
            options={'ordering': ['PagoID'], 'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.AlterModelOptions(
            name='participantesactividad',
            options={'ordering': ['ActividadParticipanteID'], 'verbose_name': 'Participante de actividad', 'verbose_name_plural': 'Participantes de actividad'},
        ),
        migrations.AlterModelOptions(
            name='participantesevento',
            options={'ordering': ['ParticipanteID'], 'verbose_name': 'Participante del evento', 'verbose_name_plural': 'Participantes del evento'},
        ),
        migrations.AlterModelOptions(
            name='saldos',
            options={'ordering': ['SaldoID'], 'verbose_name': 'Saldo', 'verbose_name_plural': 'Saldos'},
        ),
        migrations.AlterField(
            model_name='perfil',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
