# Generated by Django 4.2.6 on 2023-11-12 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_actividades_options_alter_contactos_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactos',
            name='Emisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='api.perfil', to_field='user'),
        ),
        migrations.AlterField(
            model_name='contactos',
            name='Remitente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacto', to='api.perfil', to_field='user'),
        ),
        migrations.AlterUniqueTogether(
            name='contactos',
            unique_together={('Emisor', 'Remitente'), ('Remitente', 'Emisor')},
        ),
    ]
